# Generated by Django 5.2.8 on 2025-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth_client', '0003_azure_ad_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='endpointpermission',
            new_name='hub_auth_cl_url_pat_6a85ac_idx',
            old_name='hub_auth_cl_url_pat_idx',
        ),
        migrations.RenameIndex(
            model_name='endpointpermission',
            new_name='hub_auth_cl_priorit_2c25b4_idx',
            old_name='hub_auth_cl_priorit_idx',
        ),
        migrations.AlterField(
            model_name='rlspolicy',
            name='using_expression',
            field=models.TextField(
                blank=True,
                help_text=(
                    "SQL USING expression for row visibility. Example: "
                    "department_id = current_setting('app.user_department')::int "
                    "Leave blank to use scope/role-based expression."
                ),
            ),
        ),
    ]