# Generated by Django 5.2.8 on 2025-12-10 16:05

from django.db import connection, migrations, models


def rename_indexes_forward(apps, schema_editor):
    """Rename indexes - PostgreSQL only, SQLite doesn't support ALTER INDEX."""
    if connection.vendor == 'postgresql':
        schema_editor.execute("""
            ALTER INDEX IF EXISTS hub_auth_cl_url_pat_idx
            RENAME TO hub_auth_cl_url_pat_6a85ac_idx;
        """)
        schema_editor.execute("""
            ALTER INDEX IF EXISTS hub_auth_cl_priorit_idx
            RENAME TO hub_auth_cl_priorit_2c25b4_idx;
        """)


def rename_indexes_reverse(apps, schema_editor):
    """Reverse index rename - PostgreSQL only."""
    if connection.vendor == 'postgresql':
        schema_editor.execute("""
            ALTER INDEX IF EXISTS hub_auth_cl_url_pat_6a85ac_idx
            RENAME TO hub_auth_cl_url_pat_idx;
        """)
        schema_editor.execute("""
            ALTER INDEX IF EXISTS hub_auth_cl_priorit_2c25b4_idx
            RENAME TO hub_auth_cl_priorit_idx;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth_client', '0003_azure_ad_config'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_forward, rename_indexes_reverse),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='endpointpermission',
                    old_name='hub_auth_cl_url_pat_idx',
                    new_name='hub_auth_cl_url_pat_6a85ac_idx',
                ),
                migrations.RenameIndex(
                    model_name='endpointpermission',
                    old_name='hub_auth_cl_priorit_idx',
                    new_name='hub_auth_cl_priorit_2c25b4_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='rlspolicy',
            name='using_expression',
            field=models.TextField(
                blank=True,
                help_text=(
                    "SQL USING expression for row visibility. Example: "
                    "department_id = current_setting('app.user_department')::int "
                    "Leave blank to use scope/role-based expression."
                ),
            ),
        ),
    ]
