# Generated by Django 5.2.8 on 2025-12-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth_client', '0004_rename_hub_auth_cl_url_pat_idx_hub_auth_cl_url_pat_6a85ac_idx_and_more'),
        ('hub_auth_client', '0005_remove_allowed_audiences'),
    ]

    operations = [
    ]