# Generated by Django 5.2.8 on 2025-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth_client', '0006_merge_20251210_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpointMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'API Endpoint Mapping',
                'verbose_name_plural': 'API Endpoint Mappings',
                'managed': False,
            },
        ),
    ]
